steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/rich-gift-437021-n6/talentpitch-final/talentpitch-final:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/rich-gift-437021-n6/talentpitch-final/talentpitch-final:latest']